.DEFAULT_GOAL := help
SHELL := /bin/bash

UV ?= uv
RUN := $(UV) run

.PHONY: help
help: ## Show available targets
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) \
		| sort \
		| awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-24s\033[0m %s\n", $$1, $$2}'

# ---------------------------------------------------------------------------
# Environment
# ---------------------------------------------------------------------------

.PHONY: install
install: ## Create the virtualenv and install all dependencies
	$(UV) sync --extra dev

.PHONY: lock
lock: ## Refresh uv.lock
	$(UV) lock

# ---------------------------------------------------------------------------
# Quality gates
# ---------------------------------------------------------------------------

.PHONY: format
format: ## Apply formatting and import ordering
	$(RUN) ruff format .
	$(RUN) ruff check --fix .

.PHONY: format-check
format-check: ## Verify formatting without modifying files
	$(RUN) ruff format --check .

.PHONY: lint
lint: ## Run the linter
	$(RUN) ruff check .

.PHONY: typecheck
typecheck: ## Run static type checking
	$(RUN) mypy

.PHONY: boundaries
boundaries: ## Enforce architectural import boundaries
	$(RUN) lint-imports

.PHONY: verify
verify: format-check lint typecheck boundaries test-unit ## Run the fast pre-commit gate

.PHONY: verify-all
verify-all: format-check lint typecheck boundaries test ## Run every gate including container tests

# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------

.PHONY: test
test: ## Run the full test suite
	$(RUN) pytest

.PHONY: test-unit
test-unit: ## Run unit, contract and end-to-end tests (no containers required)
	$(RUN) pytest tests/unit tests/contract tests/e2e

.PHONY: test-integration
test-integration: ## Run integration tests (requires a running Docker daemon)
	$(RUN) pytest tests/integration

.PHONY: coverage
coverage: ## Run tests with a coverage report
	$(RUN) pytest --cov --cov-report=term-missing --cov-report=xml

# ---------------------------------------------------------------------------
# Database
# ---------------------------------------------------------------------------

.PHONY: migrate
migrate: ## Apply all database migrations
	$(RUN) alembic upgrade head

.PHONY: migrate-down
migrate-down: ## Roll back the most recent migration
	$(RUN) alembic downgrade -1

.PHONY: migration
migration: ## Create a new autogenerated migration (make migration m="description")
	$(RUN) alembic revision --autogenerate -m "$(m)"

.PHONY: migration-check
migration-check: ## Fail if the models have drifted from the migrations
	$(RUN) python scripts/check_migrations.py

# ---------------------------------------------------------------------------
# Runtime
# ---------------------------------------------------------------------------

.PHONY: run-api
run-api: ## Run the API locally with reload
	$(RUN) uvicorn integration_orchestrator.api.app:create_app --factory --reload --port 8000

.PHONY: run-workers
run-workers: ## Run every background worker in one process
	$(RUN) python -m integration_orchestrator.workers.runner

.PHONY: token
token: ## Print a development JWT (make token roles="operator")
	$(RUN) python scripts/dev_token.py --roles $(or $(roles),operator)

.PHONY: demo
demo: ## Run the end-to-end demonstration scenarios against a running stack
	$(RUN) python scripts/demo.py

# ---------------------------------------------------------------------------
# Containers
# ---------------------------------------------------------------------------

.PHONY: up
up: ## Start the full local stack
	docker compose up --build -d

.PHONY: down
down: ## Stop the local stack and remove volumes
	docker compose down -v

.PHONY: logs
logs: ## Tail application logs
	docker compose logs -f api workers

.PHONY: docker-build
docker-build: ## Build the application image
	docker build -f docker/Dockerfile -t integration-orchestrator:local .

# ---------------------------------------------------------------------------
# Infrastructure
# ---------------------------------------------------------------------------

.PHONY: tf-fmt
tf-fmt: ## Check Terraform formatting
	terraform -chdir=terraform fmt -recursive -check

.PHONY: tf-validate
tf-validate: ## Validate the Terraform configuration
	terraform -chdir=terraform/environments/dev init -backend=false
	terraform -chdir=terraform/environments/dev validate

.PHONY: clean
clean: ## Remove caches and build artifacts
	rm -rf .pytest_cache .mypy_cache .ruff_cache htmlcov coverage.xml .coverage
	find . -type d -name __pycache__ -prune -exec rm -rf {} +
