"""Initial schema.

Creates the five tables the platform needs: the aggregate, the webhook receipts
written before any processing is attempted, the append-only audit trail, the
transactional outbox, and the idempotency records that make request creation
safely repeatable.

Written by hand rather than autogenerated so the partial index and the check
constraints say what they mean. Autogenerate is used for subsequent revisions and
verified against this baseline by ``make migration-check``.

Revision ID: 8f3c1a9d2b74
Revises:
Create Date: 2024-01-01 00:00:00.000000
"""

from __future__ import annotations

from typing import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "8f3c1a9d2b74"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

REQUEST_STATUSES = (
    "received",
    "validating",
    "dispatching",
    "pending",
    "succeeded",
    "failed",
    "retry_scheduled",
    "cancelled",
    "manual_review",
)

OPERATION_TYPES = (
    "resource_provision",
    "resource_deprovision",
    "resource_update",
    "access_grant",
    "access_revoke",
)

WEBHOOK_PROCESSING_STATUSES = (
    "received",
    "processed",
    "duplicate",
    "deferred",
    "rejected",
    "failed",
    "abandoned",
)

AUDIT_ACTIONS = (
    "request.received",
    "request.validated",
    "provider.selected",
    "dispatch.attempted",
    "provider.accepted",
    "provider.rejected",
    "provider.failed",
    "retry.scheduled",
    "retry.requested",
    "retry.exhausted",
    "webhook.received",
    "webhook.rejected",
    "webhook.duplicate_ignored",
    "webhook.deferred",
    "webhook.applied",
    "webhook.abandoned",
    "state.reconciled",
    "state.reconciliation_mismatch",
    "state.manual_review",
    "request.cancelled",
    "request.cancellation_rejected",
    "provider.circuit_opened",
    "provider.circuit_closed",
    "state.invalid_transition",
)

ACTOR_TYPES = (
    "api_client",
    "webhook",
    "retry_worker",
    "reconciliation_worker",
    "outbox_publisher",
    "system",
)


def _constrained(name: str, values: Sequence[str], length: int) -> sa.Enum:
    """A ``VARCHAR`` with a check constraint rather than a native enum.

    Adding a value to a native PostgreSQL enum needs DDL and, historically, an
    exclusive lock. Using a constrained string means a new status ships as a
    single fast statement instead of a coordinated deployment.
    """
    return sa.Enum(*values, name=name, native_enum=False, length=length)


def upgrade() -> None:
    op.create_table(
        "integration_requests",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column(
            "operation_type", _constrained("operation_type", OPERATION_TYPES, 48), nullable=False
        ),
        sa.Column("external_reference", sa.String(length=255), nullable=False),
        sa.Column("normalized_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("provider_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("provider_reference", sa.String(length=255), nullable=True),
        sa.Column("status", _constrained("request_status", REQUEST_STATUSES, 32), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("correlation_id", sa.String(length=128), nullable=False),
        sa.Column("last_error_code", sa.String(length=128), nullable=True),
        sa.Column("last_error_message", sa.Text(), nullable=True),
        sa.Column("last_error_category", sa.String(length=64), nullable=True),
        sa.Column("manual_review_reason", sa.Text(), nullable=True),
        sa.Column("next_retry_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False, server_default="0"),
        sa.PrimaryKeyConstraint("id", name="pk_integration_requests"),
        sa.UniqueConstraint("idempotency_key", name="uq_integration_requests_idempotency_key"),
        sa.UniqueConstraint(
            "provider",
            "provider_reference",
            name="uq_integration_requests_provider_provider_reference",
        ),
        sa.CheckConstraint(
            "attempt_count >= 0", name="ck_integration_requests_attempt_count_non_negative"
        ),
        sa.CheckConstraint("version >= 0", name="ck_integration_requests_version_non_negative"),
    )
    op.create_index(
        "ix_integration_requests_status_next_retry_at",
        "integration_requests",
        ["status", "next_retry_at"],
    )
    op.create_index(
        "ix_integration_requests_provider_created_at",
        "integration_requests",
        ["provider", "created_at"],
    )
    op.create_index(
        "ix_integration_requests_external_reference",
        "integration_requests",
        ["external_reference"],
    )
    op.create_index(
        "ix_integration_requests_created_at_id",
        "integration_requests",
        ["created_at", "id"],
    )
    op.create_index(
        "ix_integration_requests_status_updated_at",
        "integration_requests",
        ["status", "updated_at"],
    )

    op.create_table(
        "webhook_receipts",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("event_id", sa.String(length=255), nullable=False),
        sa.Column("event_type", sa.String(length=128), nullable=False),
        sa.Column("provider_reference", sa.String(length=255), nullable=True),
        sa.Column("signature_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "processing_status",
            _constrained("webhook_processing_status", WEBHOOK_PROCESSING_STATUSES, 32),
            nullable=False,
        ),
        sa.Column("integration_request_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("correlation_id", sa.String(length=128), nullable=True),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_webhook_receipts"),
        sa.UniqueConstraint("provider", "event_id", name="uq_webhook_receipts_provider_event_id"),
        sa.CheckConstraint(
            "attempt_count >= 0", name="ck_webhook_receipts_attempt_count_non_negative"
        ),
        # A receipt outlives the request it refers to: keeping the evidence is
        # the point, so the reference is cleared rather than cascading a delete.
        sa.ForeignKeyConstraint(
            ["integration_request_id"],
            ["integration_requests.id"],
            name="fk_webhook_receipts_integration_request_id_integration_requests",
            ondelete="SET NULL",
        ),
    )
    op.create_index(
        "ix_webhook_receipts_processing_status_received_at",
        "webhook_receipts",
        ["processing_status", "received_at"],
    )
    op.create_index(
        "ix_webhook_receipts_processing_status_next_attempt_at",
        "webhook_receipts",
        ["processing_status", "next_attempt_at"],
    )
    op.create_index(
        "ix_webhook_receipts_integration_request_id",
        "webhook_receipts",
        ["integration_request_id"],
    )

    op.create_table(
        "audit_events",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("aggregate_type", sa.String(length=64), nullable=False),
        sa.Column("aggregate_id", sa.String(length=128), nullable=False),
        sa.Column("action", _constrained("audit_action", AUDIT_ACTIONS, 64), nullable=False),
        sa.Column("actor", _constrained("actor_type", ACTOR_TYPES, 48), nullable=False),
        sa.Column("actor_id", sa.String(length=255), nullable=True),
        sa.Column("previous_state", sa.String(length=48), nullable=True),
        sa.Column("new_state", sa.String(length=48), nullable=True),
        sa.Column("correlation_id", sa.String(length=128), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_audit_events"),
    )
    op.create_index(
        "ix_audit_events_aggregate_type_aggregate_id_occurred_at",
        "audit_events",
        ["aggregate_type", "aggregate_id", "occurred_at"],
    )
    op.create_index("ix_audit_events_correlation_id", "audit_events", ["correlation_id"])

    op.create_table(
        "outbox_events",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("event_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("event_type", sa.String(length=128), nullable=False),
        sa.Column("event_version", sa.Integer(), nullable=False),
        sa.Column("aggregate_type", sa.String(length=64), nullable=False),
        sa.Column("aggregate_id", sa.String(length=128), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("correlation_id", sa.String(length=128), nullable=False),
        sa.Column("causation_id", sa.String(length=128), nullable=True),
        sa.Column("partition_key", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_outbox_events"),
        sa.UniqueConstraint("event_id", name="uq_outbox_events_event_id"),
        sa.CheckConstraint("event_version >= 1", name="ck_outbox_events_event_version_positive"),
        sa.CheckConstraint(
            "attempt_count >= 0", name="ck_outbox_events_attempt_count_non_negative"
        ),
    )
    op.create_index(
        "ix_outbox_events_unpublished",
        "outbox_events",
        ["next_attempt_at", "created_at"],
        postgresql_where=sa.text("published_at IS NULL"),
    )
    op.create_index(
        "ix_outbox_events_published_at_created_at",
        "outbox_events",
        ["published_at", "created_at"],
    )
    op.create_index("ix_outbox_events_aggregate_id", "outbox_events", ["aggregate_id"])

    op.create_table(
        "idempotency_records",
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("request_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("response_status", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("key", name="pk_idempotency_records"),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["integration_requests.id"],
            name="fk_idempotency_records_request_id_integration_requests",
            ondelete="CASCADE",
        ),
    )
    op.create_index("ix_idempotency_records_request_id", "idempotency_records", ["request_id"])
    op.create_index("ix_idempotency_records_expires_at", "idempotency_records", ["expires_at"])


def downgrade() -> None:
    op.drop_table("idempotency_records")
    op.drop_table("outbox_events")
    op.drop_table("audit_events")
    op.drop_table("webhook_receipts")
    op.drop_table("integration_requests")
